//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDienTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public string MAKH { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
